name: publish
on:
  workflow_dispatch:
    inputs:
      release_as_beta:
        description: "Mark as pre-release"
        required: true
        type: boolean
        default: true
      publish_github:
        description: "Publish to GitHub"
        required: true
        type: boolean
        default: true
permissions:
  contents: write
  packages: write
  
jobs:
  mod-build:
    name: üì¶ Build mod
    runs-on: macos-14
    steps:
      - name: checkout repository
        uses: actions/checkout@v3 # This is effectively git pull
      - name: setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin' # Installs java
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew # Execution workaround for unix-based systems
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3 # Speeds up build time by about 5 mins :P
      - name: Execute Gradle build
        run: ./gradlew build --warning-mode all # Builds the mod into a jar file
      - uses: actions/upload-artifact@v4.3.0
        with:
          name: build-common
          path: build/libs/
      - uses: actions/upload-artifact@v4.3.0
        with:
          name: build-fabric
          path: fabric/build/libs/
      - uses: actions/upload-artifact@v4.3.0
        with:
          name: build-forge
          path: forge/build/libs/

  publish-github:
    name: üêô Publish to GitHub
    runs-on: ubuntu-latest
    if: inputs.publish_github
    needs: mod-build
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4.1.0
        with:
          path: compiledmods/
      - uses: madhead/read-java-properties@latest
        id: read_properties
        with:
          file: gradle.properties
          all: true
      - name: process builds
        run: |
          cd compiledmods/
          ls -a -r
          mv ${{ env.mod_version }}-${{ env.mod_name }}.jar
        env:
          mod_name: ${{ steps.read_properties.outputs.archives_base_name }}
          mod_version: ${{ steps.read_properties.outputs.version }}
      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(dev|sources|javadoc).jar
          github-tag: "v${{ env.mod_version }}-${{ env.mc_version }}"
          name: "v${{ env.mod_version }}-${{ env.mc_version }}"
          version: "v${{ env.mod_version }}-${{ env.mc_version }}"
          version-type: ${{ inputs.release_as_beta && 'beta' || 'release' }}
        env:
          mod_name: ${{ steps.read_properties.outputs.archives_base_name }}
          mc_version: ${{ steps.read_properties.outputs.minecraft_version }}
          mod_version: ${{ steps.read_properties.outputs.version }}
